version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/invoice-generator
      - PORT=5000
      - JWT_SECRET=s8D5!2jM@cZ#vW7p2$J9rR8mL3&kF
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=invoice-generator
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo-data: